image: Visual Studio 2019

before_build:
- nuget restore

build:
  project: XUnit20FxTests.sln


test_script:
- '%xunit20%\xunit.console.x86 bin\Debug\XUnit20FxTests.dll -noautoreporters -xml results1.xml'